// packages/react/src/fields/Callout.tsx
import { calloutParts } from '../../../core/src/features/display';
import { classes, icons, type DisplayFieldSchema, type IconName } from '../../../core/src';
import { Icon } from '../Icon';
import type { FieldComponentProps } from '../types';

/** A notice inside the form, tinted by its tone (info, success, warning, danger). */
export function Callout({ field }: FieldComponentProps<DisplayFieldSchema>) {
    const callout = calloutParts(field, icons);
    return (
        <div role={callout.role} data-tone={callout.tone} className={callout.className}>
            <Icon name={callout.icon as IconName} svg={callout.svg} className={callout.iconClass} />
            <div className={classes.calloutContent}>
                {field.title && <p className={classes.calloutTitle}>{field.title}</p>}
                {field.body && <p className={classes.calloutBody}>{field.body}</p>}
            </div>
        </div>
    );
}

// packages/svelte/src/lib/fields/Callout.svelte
<script lang="ts">
    import { calloutParts } from '../core/features/display';
    import { classes, icons, type DisplayFieldSchema, type IconName } from '../core';
    import Icon from '../Icon.svelte';
    import type { FieldComponentProps } from '../types';

    /** A notice inside the form, tinted by its tone (info, success, warning, danger). */
    let { field }: FieldComponentProps<DisplayFieldSchema> = $props();

    const callout = $derived(calloutParts(field, icons));
</script>

<div role={callout.role} data-tone={callout.tone} class={callout.className}>
    <Icon name={callout.icon as IconName} svg={callout.svg} class={callout.iconClass} />
    <div class={classes.calloutContent}>
        {#if field.title}
            <p class={classes.calloutTitle}>{field.title}</p>
        {/if}
        {#if field.body}
            <p class={classes.calloutBody}>{field.body}</p>
        {/if}
    </div>
</div>
