// packages/react/src/fields/TimePicker.tsx
import { useRef } from 'react';
import { classes, nowTime, type TimePickerSchema } from '../../../core/src';
import { Icon } from '../Icon';
import type { FieldComponentProps } from '../types';
import { usePopover } from '../usePopover';
import { ClearButton } from './ClearButton';
import { TimeColumns, type TimePart } from './TimeColumns';

/**
 * Time popover with scrollable hour and minute columns (`minuteStep()`).
 * Closes once every column has been picked, or when the last column is picked
 * for a time that was already set.
 */
export function TimePicker({
    field,
    id,
    value,
    error,
    disabled,
    describedBy,
    onChange,
}: FieldComponentProps<TimePickerSchema>) {
    const { root, panel, open, setOpen, panelClass } = usePopover();
    const locked = disabled || field.readonly;
    const time = typeof value === 'string' ? value : '';
    const picked = useRef(new Set<TimePart>());
    const hadTime = useRef(false);

    function toggle() {
        if (locked) return;
        picked.current = new Set();
        hadTime.current = Boolean(time);
        setOpen(!open);
    }

    function pick(next: string, part: TimePart) {
        onChange(next);
        picked.current.add(part);
        const last: TimePart = field.withSeconds ? 'second' : 'minute';
        const columns: TimePart[] = field.withSeconds
            ? ['hour', 'minute', 'second']
            : ['hour', 'minute'];
        if (
            columns.every((column) => picked.current.has(column)) ||
            (part === last && hadTime.current)
        ) {
            setOpen(false);
        }
    }

    return (
        <div ref={root} className={classes.popoverAnchor}>
            <div
                className={classes.trigger}
                data-open={open || undefined}
                aria-disabled={locked || undefined}
                aria-invalid={error ? true : undefined}
            >
                <button
                    id={id}
                    type="button"
                    className={classes.triggerButton}
                    aria-haspopup="dialog"
                    aria-expanded={open}
                    aria-invalid={error ? true : undefined}
                    aria-describedby={describedBy}
                    aria-required={field.required || undefined}
                    disabled={locked}
                    autoFocus={field.autofocus}
                    onClick={toggle}
                >
                    <span className={time ? classes.triggerValue : classes.triggerPlaceholder}>
                        {time || field.placeholder || (field.withSeconds ? '--:--:--' : '--:--')}
                    </span>
                </button>
                {field.clearable && time && !locked && (
                    <ClearButton label={field.label} onClear={() => onChange('')} />
                )}
                <Icon name="clock" className={classes.icon} />
            </div>
            {open && (
                <div ref={panel} role="dialog" aria-label={field.label} className={panelClass()}>
                    <TimeColumns
                        id={id}
                        value={time}
                        withSeconds={field.withSeconds}
                        minuteStep={field.minuteStep}
                        minTime={field.minTime}
                        maxTime={field.maxTime}
                        onChange={pick}
                    />
                    <div className={classes.popoverFooter}>
                        <button
                            type="button"
                            className={classes.popoverAction}
                            onClick={() => {
                                onChange(nowTime(field.withSeconds, field.minuteStep));
                                setOpen(false);
                            }}
                        >
                            Now
                        </button>
                        <button
                            type="button"
                            className={classes.popoverAction}
                            onClick={() => {
                                onChange('');
                                setOpen(false);
                            }}
                        >
                            Clear
                        </button>
                    </div>
                </div>
            )}
        </div>
    );
}

// packages/svelte/src/lib/fields/TimePicker.svelte
<script lang="ts">
    import { classes, nowTime, type TimePickerSchema } from '../core';
    import Icon from '../Icon.svelte';
    import { createPopover } from '../popover.svelte';
    import type { FieldComponentProps } from '../types';
    import ClearButton from './ClearButton.svelte';
    import TimeColumns, { type TimePart } from './TimeColumns.svelte';

    /**
     * Time popover with scrollable hour and minute columns (`minuteStep()`).
     * Closes once every column has been picked, or when the last column is picked
     * for a time that was already set.
     */
    let {
        field,
        id,
        value = $bindable(),
        error,
        disabled,
        describedBy,
        onChange,
    }: FieldComponentProps<TimePickerSchema> = $props();

    const popover = createPopover();
    const locked = $derived(disabled || field.readonly);
    const time = $derived(typeof value === 'string' ? value : '');

    let picked = new Set<TimePart>();
    let hadTime = false;

    function update(next: unknown) {
        value = next;
        onChange?.(next);
    }

    function toggle() {
        if (locked) return;
        picked = new Set();
        hadTime = Boolean(time);
        popover.setOpen(!popover.open);
    }

    function pick(next: string, part: TimePart) {
        update(next);
        picked.add(part);
        const last: TimePart = field.withSeconds ? 'second' : 'minute';
        const columns: TimePart[] = field.withSeconds
            ? ['hour', 'minute', 'second']
            : ['hour', 'minute'];
        if (columns.every((column) => picked.has(column)) || (part === last && hadTime)) {
            popover.setOpen(false);
        }
    }
</script>

<div bind:this={popover.root} class={classes.popoverAnchor}>
    <div
        class={classes.trigger}
        data-open={popover.open || undefined}
        aria-disabled={locked || undefined}
        aria-invalid={error ? true : undefined}
    >
        <!-- svelte-ignore a11y_autofocus, a11y_role_supports_aria_props_implicit -->
        <button
            {id}
            type="button"
            class={classes.triggerButton}
            aria-haspopup="dialog"
            aria-expanded={popover.open}
            aria-invalid={error ? true : undefined}
            aria-describedby={describedBy}
            aria-required={field.required || undefined}
            disabled={locked}
            autofocus={field.autofocus}
            onclick={toggle}
        >
            <span class={time ? classes.triggerValue : classes.triggerPlaceholder}
                >{time || field.placeholder || (field.withSeconds ? '--:--:--' : '--:--')}</span
            >
        </button>
        {#if field.clearable && time && !locked}
            <ClearButton label={field.label} onClear={() => update('')} />
        {/if}
        <Icon name="clock" class={classes.icon} />
    </div>
    {#if popover.open}
        <div
            bind:this={popover.panel}
            role="dialog"
            aria-label={field.label}
            class={popover.panelClass()}
        >
            <TimeColumns
                {id}
                value={time}
                withSeconds={field.withSeconds}
                minuteStep={field.minuteStep}
                minTime={field.minTime}
                maxTime={field.maxTime}
                onChange={pick}
            />
            <div class={classes.popoverFooter}>
                <button
                    type="button"
                    class={classes.popoverAction}
                    onclick={() => {
                        update(nowTime(field.withSeconds, field.minuteStep));
                        popover.setOpen(false);
                    }}
                >
                    Now
                </button>
                <button
                    type="button"
                    class={classes.popoverAction}
                    onclick={() => {
                        update('');
                        popover.setOpen(false);
                    }}
                >
                    Clear
                </button>
            </div>
        </div>
    {/if}
</div>
