// packages/vue/src/Form.vue
<script setup lang="ts">
import { useForm } from '@inertiajs/vue3';
import { computed, nextTick, onMounted, provide, ref, shallowRef, useId, watch } from 'vue';
import {
    accentStyle,
    classes,
    cx,
    errorKeysFor,
    firstWizardStepWithError,
    formSubmitter,
    gridClass,
    groupSubmitFields,
    hasSubmitField,
    isFieldsetVisible,
    isVisible,
    scrollFormIntoView,
    scrollToFirstError,
    setPath,
    submissionTarget,
    submitButtonClass,
    submitIntent,
    validateWizardStep,
    visibleFields,
    wizardStepErrorKeys,
    wizardStepFields,
    wizardSteps,
    wizardSubmitFields,
    type FieldSchema,
    type FieldsetSchema,
    type FormErrors,
    mergeComponents,
} from '../../core/src';
import { formContextKey } from './context';
import FieldRenderer, { builtInComponents } from './FieldRenderer.vue';
import SubmitButton from './fields/SubmitButton.vue';
import Icon from './Icon.vue';
import { submitterKey } from './submitter';
import type { FormEmits, FormProps, FormSlots } from './types';
import WizardSteps from './WizardSteps.vue';

/**
 * Renders a form defined with `erag/inertia-forms` in Laravel.
 *
 *     <Form :form="form" @success="() => toast('Saved')" />
 *
 * `onBeforeSubmit` (or `@before-submit`) runs before the request; return
 * `false` to cancel it.
 */
const props = defineProps<FormProps>();
const emit = defineEmits<FormEmits>();
defineSlots<FormSlots>();

type Row =
    | { kind: 'field'; key: string; field: FieldSchema }
    | { kind: 'submit'; key: string; fields: FieldSchema[] };

interface Section {
    key: string | number;
    fieldset: FieldsetSchema;
    rows: Row[];
}

const schema = computed(() => props.form);
const formId = `erag-form-${useId().replace(/[^a-zA-Z0-9]/g, '')}`;
const root = ref<HTMLFormElement | null>(null);
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- Inertia's form data type requires `any` values.
const inertia = useForm<Record<string, any>>(props.form.data);
const data = computed<Record<string, unknown>>(() => inertia.data());
const errors = computed(() => inertia.errors as FormErrors);
const registry = computed(() => mergeComponents(builtInComponents, props.components));
const showDefaultSubmit = computed(() => !hasSubmitField(schema.value));
const submitter = shallowRef<HTMLElement | null>(null);
provide(submitterKey, submitter);
/**
 * Bound only when an accent is set, so server rendering omits an empty `style`.
 */
const accentAttributes = computed(() => {
    const style = accentStyle(props.accent ?? schema.value.accent);
    return style ? { style } : {};
});

const wizard = computed(() => schema.value.wizard ?? null);
const stepIndex = ref(0);
const checkingStep = ref(false);
const steps = computed(() => (wizard.value ? wizardSteps(schema.value, data.value) : []));
const currentStep = computed(() => Math.min(stepIndex.value, Math.max(steps.value.length - 1, 0)));
const isLastStep = computed(() => currentStep.value >= steps.value.length - 1);
const wizardSubmits = computed(() =>
    wizard.value && isLastStep.value ? wizardSubmitFields(schema.value, data.value) : [],
);

function rows(fields: FieldSchema[]): Row[] {
    return groupSubmitFields(fields).map((row) =>
        Array.isArray(row)
            ? { kind: 'submit', key: `submit:${row[0]!.name}`, fields: row }
            : { kind: 'field', key: row.name, field: row },
    );
}

/** The fieldsets to render: every visible one, or the current wizard step. */
const sections = computed<Section[]>(() => {
    if (wizard.value) {
        const fieldset = steps.value[currentStep.value];
        return fieldset
            ? [
                  {
                      key: fieldset.id ?? currentStep.value,
                      fieldset,
                      rows: rows(wizardStepFields(fieldset, data.value)),
                  },
              ]
            : [];
    }
    return schema.value.fieldsets.flatMap((fieldset, index) =>
        isFieldsetVisible(fieldset, data.value)
            ? [
                  {
                      key: fieldset.id ?? index,
                      fieldset,
                      rows: rows(
                          fieldset.fields.filter((field) =>
                              isVisible(field.visibility, data.value),
                          ),
                      ),
                  },
              ]
            : [],
    );
});

const visibleNames = computed(() =>
    visibleFields(schema.value, data.value).map((field) => field.name),
);
const visibilityKey = computed(() => visibleNames.value.join('|'));
let previouslyVisible = new Set(visibleNames.value);

/**
 * Write a (possibly dotted) path into the useForm data. Only the top-level key
 * is replaced, which keeps the reactive form and the submitted payload in sync.
 */
function writePaths(entries: Array<[name: string, value: unknown]>) {
    const next = entries.reduce(
        (carry, [name, value]) => setPath(carry, name, value),
        inertia.data() as Record<string, unknown>,
    );
    new Set(entries.map(([name]) => name.split('.')[0]!)).forEach((key) => {
        inertia[key] = next[key];
    });
}

watch(visibilityKey, () => {
    const current = new Set(visibleNames.value);
    const cleared = schema.value.fieldsets
        .flatMap((fieldset) => fieldset.fields)
        .filter(
            (field) =>
                field.clearWhenHidden &&
                previouslyVisible.has(field.name) &&
                !current.has(field.name),
        );
    previouslyVisible = current;
    if (cleared.length) {
        writePaths(cleared.map((field) => [field.name, field.emptyValue]));
    }
});

function setValue(name: string, value: unknown) {
    writePaths([[name, value]]);
    const keys = errorKeysFor(errors.value, name);
    if (keys.length) inertia.clearErrors(...keys);
}

watch(
    () => inertia.isDirty,
    (isDirty) => emit('dirtyChange', isDirty),
);

provide(formContextKey, {
    formId,
    get errors() {
        return errors.value;
    },
    get processing() {
        return inertia.processing;
    },
    get isDirty() {
        return inertia.isDirty;
    },
    get data() {
        return data.value;
    },
    get components() {
        return registry.value;
    },
    setValue,
});

/**
 * Browsers only honour `autofocus` on the first page load, so focus it on mount
 * like React's `autoFocus` does after client-side visits.
 */
onMounted(() => root.value?.querySelector<HTMLElement>('[autofocus]')?.focus());

/** Scroll once the new step or the errors have rendered. */
function scrollAfterRender(target: 'top' | 'error') {
    requestAnimationFrame(() => {
        void nextTick().then(() => {
            if (target === 'top') scrollFormIntoView(root.value);
            else scrollToFirstError(root.value);
        });
    });
}

/** Show the step with the first error and scroll to it. */
function revealErrors(next: FormErrors) {
    if (wizard.value) {
        const step = firstWizardStepWithError(steps.value, next);
        if (step !== -1) stepIndex.value = step;
    }
    if (schema.value.scrollToFirstError) scrollAfterRender('error');
}

function goToStep(index: number) {
    stepIndex.value = index;
    scrollAfterRender('top');
}

/** Check the current step on the server, then move to the next one. */
async function continueWizard() {
    const index = currentStep.value;
    const fieldset = steps.value[index];
    if (!wizard.value || !fieldset || checkingStep.value) return;
    checkingStep.value = true;
    try {
        const stepErrors = await validateWizardStep(wizard.value, index, data.value);
        const stale = wizardStepErrorKeys(fieldset, errors.value);
        if (stale.length) inertia.clearErrors(...stale);
        if (stepErrors) {
            inertia.setError(stepErrors as never);
            if (schema.value.scrollToFirstError) scrollAfterRender('error');
        } else {
            goToStep(index + 1);
        }
    } catch (error) {
        console.warn('[inertia-forms] Could not check the wizard step.', error);
    } finally {
        checkingStep.value = false;
    }
}

function submit(event: Event) {
    event.preventDefault();
    // Enter (or Continue) on any step but the last moves on instead of submitting.
    if (wizard.value && !isLastStep.value) {
        void continueWizard();
        return;
    }
    const button = formSubmitter(event);
    const intent = submitIntent(button);
    // The data passed to onBeforeSubmit includes the clicked button's intent.
    const proceed = props.onBeforeSubmit?.(
        intent ? { ...data.value, [intent.key]: intent.value } : data.value,
        {
            setErrors: (next) => {
                inertia.clearErrors();
                if (Object.keys(next).length) {
                    inertia.setError(next as never);
                    revealErrors(next);
                }
            },
        },
    );
    if (proceed === false) return;
    const action = schema.value.action;
    if (!action) {
        console.warn(
            '[inertia-forms] The form has no action. Set $actionRoute, route(), or url() on the form class.',
        );
        return;
    }
    submitter.value = button ?? root.value?.querySelector<HTMLElement>('[type="submit"]') ?? null;
    const { method, spoof } = submissionTarget(schema.value);
    inertia.transform((payload) => ({
        ...payload,
        ...(intent ? { [intent.key]: intent.value } : {}),
        ...(spoof ? { _method: spoof } : {}),
    }));
    inertia.submit(method, action, {
        forceFormData: schema.value.hasFiles,
        preserveScroll: true,
        onSuccess: (page) => {
            if (schema.value.resetOnSuccess) inertia.reset();
            emit('success', page);
        },
        onError: (validationErrors) => {
            emit('error', validationErrors as FormErrors);
            revealErrors(validationErrors as FormErrors);
        },
        onFinish: () => emit('finish'),
    });
}
</script>

<template>
    <form
        :id="formId"
        ref="root"
        novalidate
        :class="cx(classes.form, form.class)"
        v-bind="accentAttributes"
        :data-dirty="inertia.isDirty || undefined"
        @submit="submit"
    >
        <WizardSteps
            v-if="wizard && steps.length"
            :steps="steps"
            :current="currentStep"
            @select="goToStep"
        />
        <component
            :is="section.fieldset.legend ? 'fieldset' : 'div'"
            v-for="section in sections"
            :id="section.fieldset.id ?? undefined"
            :key="section.key"
            :class="cx(classes.fieldset, section.fieldset.class)"
        >
            <template v-if="section.fieldset.legend">
                <legend :class="classes.legend">{{ section.fieldset.legend }}</legend>
                <p v-if="section.fieldset.description" :class="classes.fieldsetDescription">
                    {{ section.fieldset.description }}
                </p>
            </template>
            <div :class="gridClass(section.fieldset.columns)">
                <template v-for="row in section.rows" :key="row.key">
                    <div v-if="row.kind === 'submit'" :class="classes.submitGroup">
                        <FieldRenderer
                            v-for="field in row.fields"
                            :key="field.name"
                            :field="field"
                            :form-id="formId"
                            :columns="section.fieldset.columns"
                            :data="data"
                            :errors="errors"
                            :processing="inertia.processing"
                            :components="registry"
                            @change="setValue"
                        />
                    </div>
                    <FieldRenderer
                        v-else
                        :field="row.field"
                        :form-id="formId"
                        :columns="section.fieldset.columns"
                        :data="data"
                        :errors="errors"
                        :processing="inertia.processing"
                        :components="registry"
                        @change="setValue"
                    />
                </template>
            </div>
        </component>
        <slot v-bind="{ isDirty: inertia.isDirty, processing: inertia.processing }" />
        <div v-if="wizard" :class="classes.wizardFooter">
            <button
                v-if="currentStep > 0"
                type="button"
                :class="submitButtonClass('secondary', 'md')"
                :disabled="checkingStep || inertia.processing"
                @click="goToStep(currentStep - 1)"
            >
                <Icon name="chevronLeft" :class="classes.submitIcon" />{{ wizard.backLabel }}
            </button>
            <div :class="classes.wizardActions">
                <button
                    v-if="!isLastStep"
                    type="submit"
                    :class="submitButtonClass('primary', 'md')"
                    :disabled="checkingStep || inertia.processing"
                    :aria-busy="checkingStep || undefined"
                >
                    <span v-if="checkingStep" :class="classes.submitSpinner" aria-hidden="true" />{{
                        wizard.nextLabel
                    }}<Icon v-if="!checkingStep" name="chevronRight" :class="classes.submitIcon" />
                </button>
                <template v-else-if="wizardSubmits.length">
                    <FieldRenderer
                        v-for="field in wizardSubmits"
                        :key="field.name"
                        :field="field"
                        :form-id="formId"
                        :columns="1"
                        :data="data"
                        :errors="errors"
                        :processing="inertia.processing"
                        :components="registry"
                        @change="setValue"
                    />
                </template>
                <SubmitButton
                    v-else-if="showDefaultSubmit"
                    label="Submit"
                    :processing="inertia.processing"
                />
            </div>
        </div>
        <SubmitButton
            v-else-if="showDefaultSubmit"
            label="Submit"
            :processing="inertia.processing"
        />
    </form>
</template>

// packages/react/src/Form.tsx
import { useForm } from '@inertiajs/react';
import {
    useEffect,
    useId,
    useMemo,
    useRef,
    useState,
    type CSSProperties,
    type FormEvent,
} from 'react';
import {
    classes,
    accentStyle,
    cx,
    errorKeysFor,
    firstWizardStepWithError,
    formSubmitter,
    gridClass,
    groupSubmitFields,
    hasSubmitField,
    isFieldsetVisible,
    isVisible,
    scrollFormIntoView,
    scrollToFirstError,
    setPath,
    submissionTarget,
    submitButtonClass,
    submitIntent,
    validateWizardStep,
    visibleFields,
    wizardStepErrorKeys,
    wizardStepFields,
    wizardSteps,
    wizardSubmitFields,
    type FieldSchema,
    type FieldsetSchema,
    type FormErrors,
    mergeComponents,
} from '../../core/src';
import { FormContext, type FormContextValue } from './context';
import { builtInComponents, FieldRenderer } from './FieldRenderer';
import { SubmitButton } from './fields/SubmitButton';
import { Icon } from './Icon';
import { SubmitterContext } from './submitter';
import type { FormProps } from './types';
import { WizardSteps } from './WizardSteps';

/**
 * Renders a form defined with `erag/inertia-forms` in Laravel.
 *
 *     <Form form={form} onSuccess={() => toast('Saved')} />
 */
export function Form({
    form: schema,
    components,
    className,
    accent,
    children,
    onDirtyChange,
    onBeforeSubmit,
    onSuccess,
    onError,
    onFinish,
}: FormProps) {
    const formId = `erag-form-${useId().replace(/[^a-zA-Z0-9]/g, '')}`;
    const root = useRef<HTMLFormElement>(null);
    // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Inertia's form data type requires `any` values.
    const inertia = useForm<Record<string, any>>(schema.data);
    const data = inertia.data;
    const errors = inertia.errors as FormErrors;
    const isDirty = inertia.isDirty;
    const registry = useMemo(() => mergeComponents(builtInComponents, components), [components]);
    const [submitter, setSubmitter] = useState<HTMLElement | null>(null);
    const [scrollRequest, setScrollRequest] = useState<{ target: 'top' | 'error' } | null>(null);

    const wizard = schema.wizard ?? null;
    const [stepIndex, setStepIndex] = useState(0);
    const [checkingStep, setCheckingStep] = useState(false);
    const checking = useRef(false);
    const latestErrors = useRef(errors);
    latestErrors.current = errors;
    const steps = wizard ? wizardSteps(schema, data) : [];
    const currentStep = Math.min(stepIndex, Math.max(steps.length - 1, 0));
    const isLastStep = currentStep >= steps.length - 1;

    const visibleNames = visibleFields(schema, data).map((field) => field.name);
    const visibilityKey = visibleNames.join('|');
    const previouslyVisible = useRef(new Set(visibleNames));

    useEffect(() => {
        const current = new Set(visibleNames);
        const cleared = schema.fieldsets
            .flatMap((fieldset) => fieldset.fields)
            .filter(
                (field) =>
                    field.clearWhenHidden &&
                    previouslyVisible.current.has(field.name) &&
                    !current.has(field.name),
            );
        previouslyVisible.current = current;
        if (cleared.length) {
            inertia.setData((previous: Record<string, unknown>) =>
                cleared.reduce(
                    (next, field) => setPath(next, field.name, field.emptyValue),
                    previous,
                ),
            );
        }
        // Only react to visibility changes.
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [visibilityKey]);

    const wasDirty = useRef(false);
    useEffect(() => {
        if (wasDirty.current === isDirty) return;
        wasDirty.current = isDirty;
        onDirtyChange?.(isDirty);
        // Only react to dirty state changes.
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [isDirty]);

    // Scroll once the new step or the errors have rendered.
    useEffect(() => {
        if (!scrollRequest) return;
        const frame = requestAnimationFrame(() => {
            if (scrollRequest.target === 'top') scrollFormIntoView(root.current);
            else scrollToFirstError(root.current);
        });
        return () => cancelAnimationFrame(frame);
    }, [scrollRequest]);

    function setValue(name: string, value: unknown) {
        inertia.setData((previous: Record<string, unknown>) => setPath(previous, name, value));
        const keys = errorKeysFor(errors, name);
        if (keys.length) inertia.clearErrors(...keys);
    }

    const context: FormContextValue = {
        formId,
        errors,
        processing: inertia.processing,
        isDirty,
        data,
        components: registry,
        setValue,
    };

    /** Show the step with the first error and scroll to it. */
    function revealErrors(next: FormErrors) {
        if (wizard) {
            const step = firstWizardStepWithError(wizardSteps(schema, data), next);
            if (step !== -1) setStepIndex(step);
        }
        if (schema.scrollToFirstError) setScrollRequest({ target: 'error' });
    }

    function goToStep(index: number) {
        setStepIndex(index);
        setScrollRequest({ target: 'top' });
    }

    /** Check the current step on the server, then move to the next one. */
    async function continueWizard() {
        const fieldset = steps[currentStep];
        if (!wizard || !fieldset || checking.current) return;
        checking.current = true;
        setCheckingStep(true);
        try {
            const stepErrors = await validateWizardStep(wizard, currentStep, data);
            const stale = wizardStepErrorKeys(fieldset, latestErrors.current);
            if (stale.length) inertia.clearErrors(...stale);
            if (stepErrors) {
                inertia.setError(stepErrors as never);
                if (schema.scrollToFirstError) setScrollRequest({ target: 'error' });
            } else {
                goToStep(currentStep + 1);
            }
        } catch (error) {
            console.warn('[inertia-forms] Could not check the wizard step.', error);
        } finally {
            checking.current = false;
            setCheckingStep(false);
        }
    }

    function submit(event: FormEvent<HTMLFormElement>) {
        event.preventDefault();
        // Enter (or Continue) on any step but the last moves on instead of submitting.
        if (wizard && !isLastStep) {
            void continueWizard();
            return;
        }
        const button = formSubmitter(event.nativeEvent);
        const intent = submitIntent(button);
        // The data passed to onBeforeSubmit includes the clicked button's intent.
        const proceed = onBeforeSubmit?.(intent ? { ...data, [intent.key]: intent.value } : data, {
            setErrors: (next) => {
                inertia.clearErrors();
                if (Object.keys(next).length) {
                    inertia.setError(next as never);
                    revealErrors(next);
                }
            },
        });
        if (proceed === false) return;
        if (!schema.action) {
            console.warn(
                '[inertia-forms] The form has no action. Set $actionRoute, route(), or url() on the form class.',
            );
            return;
        }
        setSubmitter(button ?? root.current?.querySelector<HTMLElement>('[type="submit"]') ?? null);
        const { method, spoof } = submissionTarget(schema);
        inertia.transform((payload) => ({
            ...payload,
            ...(intent ? { [intent.key]: intent.value } : {}),
            ...(spoof ? { _method: spoof } : {}),
        }));
        inertia.submit(method, schema.action, {
            forceFormData: schema.hasFiles,
            preserveScroll: true,
            onSuccess: (page) => {
                if (schema.resetOnSuccess) inertia.reset();
                onSuccess?.(page);
            },
            onError: (validationErrors) => {
                onError?.(validationErrors as FormErrors);
                revealErrors(validationErrors as FormErrors);
            },
            onFinish: () => onFinish?.(),
        });
    }

    const extra =
        typeof children === 'function'
            ? children({ isDirty, processing: inertia.processing })
            : children;

    function renderField(field: FieldSchema, columns: number) {
        return (
            <FieldRenderer
                key={field.name}
                field={field}
                formId={formId}
                columns={columns}
                data={data}
                errors={errors}
                processing={inertia.processing}
                components={registry}
                onChange={setValue}
            />
        );
    }

    function renderFieldset(fieldset: FieldsetSchema, key: string | number, fields: FieldSchema[]) {
        const grid = (
            <div className={gridClass(fieldset.columns)}>
                {groupSubmitFields(fields).map((row) =>
                    Array.isArray(row) ? (
                        <div key={`submit:${row[0]!.name}`} className={classes.submitGroup}>
                            {row.map((field) => renderField(field, fieldset.columns))}
                        </div>
                    ) : (
                        renderField(row, fieldset.columns)
                    ),
                )}
            </div>
        );

        if (!fieldset.legend) {
            return (
                <div
                    key={key}
                    id={fieldset.id ?? undefined}
                    className={cx(classes.fieldset, fieldset.class)}
                >
                    {grid}
                </div>
            );
        }

        return (
            <fieldset
                key={key}
                id={fieldset.id ?? undefined}
                className={cx(classes.fieldset, fieldset.class)}
            >
                <legend className={classes.legend}>{fieldset.legend}</legend>
                {fieldset.description && (
                    <p className={classes.fieldsetDescription}>{fieldset.description}</p>
                )}
                {grid}
            </fieldset>
        );
    }

    function renderWizard() {
        if (!wizard) return null;
        const fieldset = steps[currentStep];
        const submitFields = isLastStep ? wizardSubmitFields(schema, data) : [];
        const busy = checkingStep || inertia.processing;

        return (
            <>
                {steps.length > 0 && (
                    <WizardSteps steps={steps} current={currentStep} onSelect={goToStep} />
                )}
                {fieldset &&
                    renderFieldset(
                        fieldset,
                        fieldset.id ?? currentStep,
                        wizardStepFields(fieldset, data),
                    )}
                {extra}
                <div className={classes.wizardFooter}>
                    {currentStep > 0 && (
                        <button
                            type="button"
                            className={submitButtonClass('secondary', 'md')}
                            disabled={busy}
                            onClick={() => goToStep(currentStep - 1)}
                        >
                            <Icon name="chevronLeft" className={classes.submitIcon} />
                            {wizard.backLabel}
                        </button>
                    )}
                    <div className={classes.wizardActions}>
                        {!isLastStep ? (
                            <button
                                type="submit"
                                className={submitButtonClass('primary', 'md')}
                                disabled={busy}
                                aria-busy={checkingStep || undefined}
                            >
                                {checkingStep && (
                                    <span className={classes.submitSpinner} aria-hidden="true" />
                                )}
                                {wizard.nextLabel}
                                {!checkingStep && (
                                    <Icon name="chevronRight" className={classes.submitIcon} />
                                )}
                            </button>
                        ) : submitFields.length ? (
                            submitFields.map((field) => renderField(field, 1))
                        ) : (
                            !hasSubmitField(schema) && (
                                <SubmitButton label="Submit" processing={inertia.processing} />
                            )
                        )}
                    </div>
                </div>
            </>
        );
    }

    return (
        <FormContext.Provider value={context}>
            <SubmitterContext.Provider value={submitter}>
                <form
                    ref={root}
                    id={formId}
                    noValidate
                    className={cx(classes.form, schema.class, className)}
                    style={accentStyle(accent ?? schema.accent) as CSSProperties | undefined}
                    data-dirty={isDirty || undefined}
                    onSubmit={submit}
                >
                    {wizard ? (
                        renderWizard()
                    ) : (
                        <>
                            {schema.fieldsets.map((fieldset, index) =>
                                isFieldsetVisible(fieldset, data)
                                    ? renderFieldset(
                                          fieldset,
                                          fieldset.id ?? index,
                                          fieldset.fields.filter((field) =>
                                              isVisible(field.visibility, data),
                                          ),
                                      )
                                    : null,
                            )}
                            {extra}
                            {!hasSubmitField(schema) && (
                                <SubmitButton label="Submit" processing={inertia.processing} />
                            )}
                        </>
                    )}
                </form>
            </SubmitterContext.Provider>
        </FormContext.Provider>
    );
}
