// packages/svelte/src/lib/fields/Checkbox.svelte
<script lang="ts">
    import { classes, type BooleanFieldSchema } from '../core';
    import type { FieldComponentProps } from '../types';

    let {
        field,
        id,
        value = $bindable(),
        error,
        disabled,
        describedBy,
        onChange,
    }: FieldComponentProps<BooleanFieldSchema> = $props();

    function update(next: unknown) {
        value = next;
        onChange?.(next);
    }
</script>

<label for={id} class={classes.choice}>
    <!-- svelte-ignore a11y_autofocus -->
    <input
        {id}
        name={field.name}
        type="checkbox"
        checked={value === field.trueValue}
        required={field.required}
        disabled={disabled || field.readonly}
        autofocus={field.autofocus}
        aria-invalid={error ? true : undefined}
        aria-describedby={describedBy}
        class={classes.checkbox}
        onchange={(event) =>
            update(event.currentTarget.checked ? field.trueValue : field.falseValue)}
    />
    <span class={classes.choiceText}>
        <span class={classes.choiceLabel}
            >{field.label}{#if field.required}<span class={classes.required} aria-hidden="true"
                    >*</span
                >{/if}</span
        >
    </span>
</label>

// packages/react/src/fields/Checkbox.tsx
import { classes, type BooleanFieldSchema } from '../../../core/src';
import type { FieldComponentProps } from '../types';

export function Checkbox({
    field,
    id,
    value,
    error,
    disabled,
    describedBy,
    onChange,
}: FieldComponentProps<BooleanFieldSchema>) {
    return (
        <label htmlFor={id} className={classes.choice}>
            <input
                id={id}
                name={field.name}
                type="checkbox"
                checked={value === field.trueValue}
                required={field.required}
                disabled={disabled || field.readonly}
                autoFocus={field.autofocus}
                aria-invalid={error ? true : undefined}
                aria-describedby={describedBy}
                className={classes.checkbox}
                onChange={(event) =>
                    onChange(event.target.checked ? field.trueValue : field.falseValue)
                }
            />
            <span className={classes.choiceText}>
                <span className={classes.choiceLabel}>
                    {field.label}
                    {field.required && (
                        <span className={classes.required} aria-hidden="true">
                            *
                        </span>
                    )}
                </span>
            </span>
        </label>
    );
}
