// packages/svelte/src/lib/fields/Composer.svelte
<script lang="ts">
    import {
        addComposerAttachments,
        classes,
        composerAccept,
        composerHasRoom,
        composerValue,
        dragHasFiles,
        formatFileSize,
        type ComposerSchema,
        type ComposerValue,
    } from '../core';
    import { getFormContext } from '../context';
    import Icon from '../Icon.svelte';
    import type { FieldComponentProps } from '../types';

    let {
        field,
        id,
        value = $bindable(),
        error,
        disabled,
        describedBy,
        onChange,
    }: FieldComponentProps<ComposerSchema> = $props();

    const form = getFormContext();
    let textarea = $state<HTMLTextAreaElement | null>(null);
    let fileInput = $state<HTMLInputElement | null>(null);
    let sendButton = $state<HTMLButtonElement | null>(null);
    let dragging = $state(false);
    const current = $derived(composerValue(value));
    const processing = $derived(form?.processing ?? false);
    const locked = $derived(disabled || field.readonly);
    const canAttach = $derived(
        field.attachments && !locked && composerHasRoom(field, current.attachments.length),
    );
    const showHint = $derived(field.submitOnEnter && !locked);
    const hintId = $derived(`${id}-hint`);
    const ariaDescribedBy = $derived(
        [describedBy, showHint ? hintId : null].filter(Boolean).join(' ') || undefined,
    );

    $effect(() => {
        void current.message;
        if (!textarea) return;
        textarea.style.height = 'auto';
        textarea.style.height = `${textarea.scrollHeight}px`;
    });

    function update(next: Partial<ComposerValue>) {
        const merged = { ...current, ...next };
        value = merged;
        onChange?.(merged);
    }

    function addFiles(list: FileList | null | undefined) {
        const picked = Array.from(list ?? []);
        if (fileInput) fileInput.value = '';
        if (!picked.length || !canAttach) return;
        update({ attachments: addComposerAttachments(current.attachments, picked, field) });
    }

    function removeFile(index: number) {
        update({ attachments: current.attachments.filter((_, position) => position !== index) });
    }

    function send() {
        const button = sendButton;
        if (!button || button.disabled || !button.form) return;
        if (typeof button.form.requestSubmit === 'function') button.form.requestSubmit(button);
        else button.click();
    }

    function keydown(event: KeyboardEvent) {
        if (
            event.key !== 'Enter' ||
            event.shiftKey ||
            event.isComposing ||
            event.keyCode === 229 ||
            !field.submitOnEnter ||
            locked
        )
            return;
        event.preventDefault();
        send();
    }

    function dragover(event: DragEvent) {
        if (!field.attachments || locked || !dragHasFiles(event.dataTransfer)) return;
        event.preventDefault();
        dragging = true;
    }

    function drop(event: DragEvent) {
        if (!field.attachments || locked || !dragHasFiles(event.dataTransfer)) return;
        event.preventDefault();
        dragging = false;
        addFiles(event.dataTransfer?.files);
    }
</script>

<div class={classes.composer}>
    {#if field.quickReplies.length > 0}
        <div role="group" aria-label="Quick replies" class={classes.composerReplies}>
            {#each field.quickReplies as reply, index (`${reply}-${index}`)}
                <button
                    type="button"
                    class={classes.composerReply}
                    disabled={locked}
                    onclick={() => {
                        update({ message: reply });
                        textarea?.focus();
                    }}>{reply}</button
                >
            {/each}
        </div>
    {/if}
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div
        class={classes.composerBox}
        data-dragging={dragging ? '' : undefined}
        data-disabled={locked ? '' : undefined}
        ondragover={dragover}
        ondragleave={() => (dragging = false)}
        ondrop={drop}
    >
        <!-- svelte-ignore a11y_autofocus -->
        <textarea
            bind:this={textarea}
            {id}
            name={`${field.name}[message]`}
            rows={field.rows}
            value={current.message}
            placeholder={field.placeholder ?? undefined}
            {disabled}
            readonly={field.readonly}
            autofocus={field.autofocus}
            maxlength={field.maxLength ?? undefined}
            aria-required={field.required || undefined}
            aria-invalid={error ? true : undefined}
            aria-describedby={ariaDescribedBy}
            class={classes.composerInput}
            oninput={(event) => update({ message: event.currentTarget.value })}
            onkeydown={keydown}
        ></textarea>
        {#if current.attachments.length > 0}
            <div role="list" aria-label="Attachments" class={classes.composerFiles}>
                {#each current.attachments as file, index (`${file.name}-${index}`)}
                    <div role="listitem" class={classes.composerFile}>
                        <span class={classes.composerFileIcon} aria-hidden="true">
                            <Icon name="composerFile" class={classes.composerFileGlyph} />
                        </span>
                        <span class={classes.composerFileText}>
                            <span class={classes.composerFileName} title={file.name}
                                >{file.name}</span
                            >
                            <span class={classes.composerFileSize}>{formatFileSize(file.size)}</span
                            >
                        </span>
                        {#if !locked}
                            <button
                                type="button"
                                class={classes.composerFileRemove}
                                aria-label={`Remove ${file.name}`}
                                onclick={() => removeFile(index)}
                            >
                                <Icon name="x" class={classes.composerRemoveIcon} />
                            </button>
                        {/if}
                    </div>
                {/each}
            </div>
        {/if}
        <div class={classes.composerFooter}>
            {#if field.attachments}
                <button
                    type="button"
                    class={classes.composerAttach}
                    title="Attach files"
                    aria-label="Attach files"
                    aria-controls={`${id}-files`}
                    disabled={!canAttach}
                    onclick={() => fileInput?.click()}
                >
                    <Icon name="composerPaperclip" class={classes.composerAttachIcon} />
                </button>
                <input
                    bind:this={fileInput}
                    id={`${id}-files`}
                    name={`${field.name}[attachments][]`}
                    type="file"
                    class={classes.visuallyHidden}
                    tabindex={-1}
                    aria-hidden="true"
                    multiple
                    accept={composerAccept(field.accept)}
                    disabled={!canAttach}
                    onchange={(event) => addFiles(event.currentTarget.files)}
                />
            {/if}
            <div class={classes.composerActions}>
                {#if field.maxLength !== null}
                    <span class={classes.composerCounter}
                        >{`${current.message.length} / ${field.maxLength}`}</span
                    >
                {/if}
                <button
                    bind:this={sendButton}
                    type="submit"
                    class={classes.composerSend}
                    disabled={locked || processing}
                    aria-busy={processing || undefined}
                >
                    {field.sendLabel}
                    {#if processing}
                        <span class={classes.spinner} aria-hidden="true"></span>
                    {:else}
                        <Icon name="composerSend" class={classes.composerSendIcon} />
                    {/if}
                </button>
            </div>
        </div>
    </div>
    {#if showHint}
        <p id={hintId} class={classes.composerHint}>
            Press <kbd class={classes.composerKbd}>Enter</kbd> to send,
            <kbd class={classes.composerKbd}>Shift + Enter</kbd> for new line
        </p>
    {/if}
</div>

// packages/react/src/fields/Composer.tsx
import { useLayoutEffect, useRef, useState, type DragEvent, type KeyboardEvent } from 'react';
import {
    addComposerAttachments,
    classes,
    composerAccept,
    composerHasRoom,
    composerValue,
    dragHasFiles,
    formatFileSize,
    type ComposerSchema,
    type ComposerValue,
} from '../../../core/src';
import { useFormContext } from '../context';
import { Icon } from '../Icon';
import type { FieldComponentProps } from '../types';

export function Composer({
    field,
    id,
    value,
    error,
    disabled,
    describedBy,
    onChange,
}: FieldComponentProps<ComposerSchema>) {
    const processing = useFormContext()?.processing ?? false;
    const textarea = useRef<HTMLTextAreaElement>(null);
    const fileInput = useRef<HTMLInputElement>(null);
    const sendButton = useRef<HTMLButtonElement>(null);
    const [dragging, setDragging] = useState(false);
    const current = composerValue(value);
    const locked = disabled || field.readonly;
    const canAttach =
        field.attachments && !locked && composerHasRoom(field, current.attachments.length);
    const showHint = field.submitOnEnter && !locked;
    const hintId = `${id}-hint`;
    const ariaDescribedBy = [describedBy, showHint ? hintId : null].filter(Boolean).join(' ');

    useLayoutEffect(() => {
        const element = textarea.current;
        if (!element) return;
        element.style.height = 'auto';
        element.style.height = `${element.scrollHeight}px`;
    }, [current.message]);

    function update(next: Partial<ComposerValue>) {
        onChange({ ...current, ...next });
    }

    function addFiles(list: FileList | null | undefined) {
        const picked = Array.from(list ?? []);
        if (fileInput.current) fileInput.current.value = '';
        if (!picked.length || !canAttach) return;
        update({ attachments: addComposerAttachments(current.attachments, picked, field) });
    }

    function removeFile(index: number) {
        update({ attachments: current.attachments.filter((_, position) => position !== index) });
    }

    function send() {
        const button = sendButton.current;
        if (!button || button.disabled || !button.form) return;
        if (typeof button.form.requestSubmit === 'function') button.form.requestSubmit(button);
        else button.click();
    }

    function keyDown(event: KeyboardEvent<HTMLTextAreaElement>) {
        if (
            event.key !== 'Enter' ||
            event.shiftKey ||
            event.nativeEvent.isComposing ||
            event.keyCode === 229 ||
            !field.submitOnEnter ||
            locked
        )
            return;
        event.preventDefault();
        send();
    }

    function dragOver(event: DragEvent<HTMLDivElement>) {
        if (!field.attachments || locked || !dragHasFiles(event.dataTransfer)) return;
        event.preventDefault();
        setDragging(true);
    }

    function drop(event: DragEvent<HTMLDivElement>) {
        if (!field.attachments || locked || !dragHasFiles(event.dataTransfer)) return;
        event.preventDefault();
        setDragging(false);
        addFiles(event.dataTransfer.files);
    }

    return (
        <div className={classes.composer}>
            {field.quickReplies.length > 0 && (
                <div role="group" aria-label="Quick replies" className={classes.composerReplies}>
                    {field.quickReplies.map((reply, index) => (
                        <button
                            key={`${reply}-${index}`}
                            type="button"
                            className={classes.composerReply}
                            disabled={locked}
                            onClick={() => {
                                update({ message: reply });
                                textarea.current?.focus();
                            }}
                        >
                            {reply}
                        </button>
                    ))}
                </div>
            )}
            <div
                className={classes.composerBox}
                data-dragging={dragging ? '' : undefined}
                data-disabled={locked ? '' : undefined}
                onDragOver={dragOver}
                onDragLeave={() => setDragging(false)}
                onDrop={drop}
            >
                <textarea
                    ref={textarea}
                    id={id}
                    name={`${field.name}[message]`}
                    rows={field.rows}
                    value={current.message}
                    placeholder={field.placeholder ?? undefined}
                    disabled={disabled}
                    readOnly={field.readonly}
                    autoFocus={field.autofocus}
                    maxLength={field.maxLength ?? undefined}
                    aria-required={field.required || undefined}
                    aria-invalid={error ? true : undefined}
                    aria-describedby={ariaDescribedBy || undefined}
                    className={classes.composerInput}
                    onChange={(event) => update({ message: event.target.value })}
                    onKeyDown={keyDown}
                />
                {current.attachments.length > 0 && (
                    <div role="list" aria-label="Attachments" className={classes.composerFiles}>
                        {current.attachments.map((file, index) => (
                            <div
                                role="listitem"
                                key={`${file.name}-${index}`}
                                className={classes.composerFile}
                            >
                                <span className={classes.composerFileIcon} aria-hidden="true">
                                    <Icon
                                        name="composerFile"
                                        className={classes.composerFileGlyph}
                                    />
                                </span>
                                <span className={classes.composerFileText}>
                                    <span className={classes.composerFileName} title={file.name}>
                                        {file.name}
                                    </span>
                                    <span className={classes.composerFileSize}>
                                        {formatFileSize(file.size)}
                                    </span>
                                </span>
                                {!locked && (
                                    <button
                                        type="button"
                                        className={classes.composerFileRemove}
                                        aria-label={`Remove ${file.name}`}
                                        onClick={() => removeFile(index)}
                                    >
                                        <Icon name="x" className={classes.composerRemoveIcon} />
                                    </button>
                                )}
                            </div>
                        ))}
                    </div>
                )}
                <div className={classes.composerFooter}>
                    {field.attachments && (
                        <>
                            <button
                                type="button"
                                className={classes.composerAttach}
                                title="Attach files"
                                aria-label="Attach files"
                                aria-controls={`${id}-files`}
                                disabled={!canAttach}
                                onClick={() => fileInput.current?.click()}
                            >
                                <Icon
                                    name="composerPaperclip"
                                    className={classes.composerAttachIcon}
                                />
                            </button>
                            <input
                                ref={fileInput}
                                id={`${id}-files`}
                                name={`${field.name}[attachments][]`}
                                type="file"
                                className={classes.visuallyHidden}
                                tabIndex={-1}
                                aria-hidden="true"
                                multiple
                                accept={composerAccept(field.accept)}
                                disabled={!canAttach}
                                onChange={(event) => addFiles(event.target.files)}
                            />
                        </>
                    )}
                    <div className={classes.composerActions}>
                        {field.maxLength !== null && (
                            <span className={classes.composerCounter}>
                                {`${current.message.length} / ${field.maxLength}`}
                            </span>
                        )}
                        <button
                            ref={sendButton}
                            type="submit"
                            className={classes.composerSend}
                            disabled={locked || processing}
                            aria-busy={processing || undefined}
                        >
                            {field.sendLabel}
                            {processing ? (
                                <span className={classes.spinner} aria-hidden="true" />
                            ) : (
                                <Icon name="composerSend" className={classes.composerSendIcon} />
                            )}
                        </button>
                    </div>
                </div>
            </div>
            {showHint && (
                <p id={hintId} className={classes.composerHint}>
                    Press <kbd className={classes.composerKbd}>Enter</kbd> to send,{' '}
                    <kbd className={classes.composerKbd}>Shift + Enter</kbd> for new line
                </p>
            )}
        </div>
    );
}
