// packages/svelte/src/lib/fields/Radio.svelte
<script lang="ts">
    import { choiceListClass, classes, type ChoiceListSchema } from '../core';
    import type { FieldComponentProps } from '../types';

    let {
        field,
        id,
        value = $bindable(),
        error,
        disabled,
        describedBy,
        onChange,
    }: FieldComponentProps<ChoiceListSchema> = $props();

    const cards = $derived(field.options.some((option) => option.description));

    function update(next: unknown) {
        value = next;
        onChange?.(next);
    }
</script>

{#if field.buttons}
    <div
        role="radiogroup"
        aria-labelledby={`${id}-label`}
        aria-describedby={describedBy}
        aria-invalid={error ? true : undefined}
        class={classes.segmented}
    >
        {#each field.options as option, index (String(option.value))}
            <label class={classes.segment}>
                <!-- svelte-ignore a11y_autofocus -->
                <input
                    id={`${id}-${index}`}
                    type="radio"
                    name={field.name}
                    value={String(option.value)}
                    checked={String(value) === String(option.value) && value !== null}
                    disabled={disabled || field.readonly || option.disabled}
                    autofocus={field.autofocus && index === 0}
                    class={classes.visuallyHidden}
                    onchange={() => update(option.value)}
                />{option.label}</label
            >
        {/each}
    </div>
{:else}
    <div
        role="radiogroup"
        aria-labelledby={`${id}-label`}
        aria-describedby={describedBy}
        aria-invalid={error ? true : undefined}
        class={choiceListClass(field.inline, field.columns)}
    >
        {#each field.options as option, index (String(option.value))}
            {@const optionId = `${id}-${index}`}
            <label for={optionId} class={cards ? classes.choiceCard : classes.choice}>
                <!-- svelte-ignore a11y_autofocus -->
                <input
                    id={optionId}
                    type="radio"
                    name={field.name}
                    value={String(option.value)}
                    checked={String(value) === String(option.value) && value !== null}
                    required={field.required}
                    disabled={disabled || field.readonly || option.disabled}
                    autofocus={field.autofocus && index === 0}
                    class={classes.radio}
                    onchange={() => update(option.value)}
                />
                <span class={classes.choiceText}>
                    <span class={classes.choiceLabel}>{option.label}</span>
                    {#if option.description}
                        <span class={classes.choiceDescription}>{option.description}</span>
                    {/if}
                </span>
            </label>
        {/each}
    </div>
{/if}

// packages/react/src/fields/Radio.tsx
import {
    choiceListClass,
    classes,
    type ChoiceListSchema,
    type FieldOption,
} from '../../../core/src';
import type { FieldComponentProps } from '../types';

export function Radio({
    field,
    id,
    value,
    error,
    disabled,
    describedBy,
    onChange,
}: FieldComponentProps<ChoiceListSchema>) {
    const cards = field.options.some((option) => option.description);

    if (field.buttons) {
        return (
            <div
                role="radiogroup"
                aria-labelledby={`${id}-label`}
                aria-describedby={describedBy}
                aria-invalid={error ? true : undefined}
                className={classes.segmented}
            >
                {field.options.map((option: FieldOption, index) => (
                    <label key={String(option.value)} className={classes.segment}>
                        <input
                            id={`${id}-${index}`}
                            type="radio"
                            name={field.name}
                            value={String(option.value)}
                            checked={String(value) === String(option.value) && value !== null}
                            disabled={disabled || field.readonly || option.disabled}
                            autoFocus={field.autofocus && index === 0}
                            className={classes.visuallyHidden}
                            onChange={() => onChange(option.value)}
                        />
                        {option.label}
                    </label>
                ))}
            </div>
        );
    }

    return (
        <div
            role="radiogroup"
            aria-labelledby={`${id}-label`}
            aria-describedby={describedBy}
            aria-invalid={error ? true : undefined}
            className={choiceListClass(field.inline, field.columns)}
        >
            {field.options.map((option: FieldOption, index) => {
                const optionId = `${id}-${index}`;
                return (
                    <label
                        key={String(option.value)}
                        htmlFor={optionId}
                        className={cards ? classes.choiceCard : classes.choice}
                    >
                        <input
                            id={optionId}
                            type="radio"
                            name={field.name}
                            value={String(option.value)}
                            checked={String(value) === String(option.value) && value !== null}
                            required={field.required}
                            disabled={disabled || field.readonly || option.disabled}
                            autoFocus={field.autofocus && index === 0}
                            className={classes.radio}
                            onChange={() => onChange(option.value)}
                        />
                        <span className={classes.choiceText}>
                            <span className={classes.choiceLabel}>{option.label}</span>
                            {option.description && (
                                <span className={classes.choiceDescription}>
                                    {option.description}
                                </span>
                            )}
                        </span>
                    </label>
                );
            })}
        </div>
    );
}
