// packages/svelte/src/lib/fields/TextInput.svelte
<script lang="ts">
    import { classes, cx, preventNumberWheel, type TextInputSchema } from '../core';
    import type { FieldComponentProps } from '../types';
    import ClearButton from './ClearButton.svelte';

    let {
        field,
        id,
        value = $bindable(),
        error,
        disabled,
        describedBy,
        onChange,
    }: FieldComponentProps<TextInputSchema> = $props();

    const text = $derived(value === null || value === undefined ? '' : String(value));
    const showClear = $derived(field.clearable && text !== '' && !disabled && !field.readonly);
    const grouped = $derived(Boolean(field.prefix || field.suffix || field.clearable));

    function update(next: unknown) {
        value = next;
        onChange?.(next);
    }

    /** Svelte registers `onwheel` as passive, so add a listener that can cancel the step. */
    function numberWheel(node: HTMLInputElement) {
        node.addEventListener('wheel', preventNumberWheel, { passive: false });
        return { destroy: () => node.removeEventListener('wheel', preventNumberWheel) };
    }
</script>

{#snippet input()}
    <!-- svelte-ignore a11y_autofocus -->
    <input
        {id}
        name={field.name}
        type={field.type}
        value={text}
        placeholder={field.placeholder ?? undefined}
        required={field.required}
        {disabled}
        readonly={field.readonly}
        autofocus={field.autofocus}
        autocomplete={(field.autocomplete ?? undefined) as HTMLInputElement['autocomplete']}
        minlength={field.minLength ?? undefined}
        maxlength={field.maxLength ?? undefined}
        min={field.min ?? undefined}
        max={field.max ?? undefined}
        step={field.step ?? undefined}
        aria-invalid={error ? true : undefined}
        aria-describedby={describedBy}
        class={grouped ? classes.inputGroupInput : classes.input}
        oninput={(event) => update(event.currentTarget.value)}
        use:numberWheel
    />
{/snippet}

{#if !grouped}
    {@render input()}
{:else}
    <div class={cx(classes.inputGroup)}>
        {#if field.prefix}
            <span class={classes.addon}>{field.prefix}</span>
        {/if}
        {@render input()}
        {#if showClear}
            <span class={classes.addonEnd}>
                <ClearButton label={field.label} onClear={() => update('')} />
            </span>
        {/if}
        {#if field.suffix}
            <span class={classes.addon}>{field.suffix}</span>
        {/if}
    </div>
{/if}

// packages/react/src/fields/TextInput.tsx
import { useEffect, useRef } from 'react';
import { classes, cx, preventNumberWheel, type TextInputSchema } from '../../../core/src';
import type { FieldComponentProps } from '../types';
import { ClearButton } from './ClearButton';

export function TextInput({
    field,
    id,
    value,
    error,
    disabled,
    describedBy,
    onChange,
}: FieldComponentProps<TextInputSchema>) {
    const text = value === null || value === undefined ? '' : String(value);
    const showClear = field.clearable && text !== '' && !disabled && !field.readonly;
    const grouped = Boolean(field.prefix || field.suffix || field.clearable);
    const inputRef = useRef<HTMLInputElement>(null);

    // React's own wheel handlers are passive, so they can't stop the value from changing.
    useEffect(() => {
        const element = inputRef.current;
        if (!element) return;
        element.addEventListener('wheel', preventNumberWheel, { passive: false });
        return () => element.removeEventListener('wheel', preventNumberWheel);
    }, [grouped]);
    const input = (
        <input
            ref={inputRef}
            id={id}
            name={field.name}
            type={field.type}
            value={value === null || value === undefined ? '' : String(value)}
            placeholder={field.placeholder ?? undefined}
            required={field.required}
            disabled={disabled}
            readOnly={field.readonly}
            autoFocus={field.autofocus}
            autoComplete={field.autocomplete ?? undefined}
            minLength={field.minLength ?? undefined}
            maxLength={field.maxLength ?? undefined}
            min={field.min ?? undefined}
            max={field.max ?? undefined}
            step={field.step ?? undefined}
            aria-invalid={error ? true : undefined}
            aria-describedby={describedBy}
            className={grouped ? classes.inputGroupInput : classes.input}
            onChange={(event) => onChange(event.target.value)}
        />
    );

    if (!grouped) return input;

    return (
        <div className={cx(classes.inputGroup)}>
            {field.prefix && <span className={classes.addon}>{field.prefix}</span>}
            {input}
            {showClear && (
                <span className={classes.addonEnd}>
                    <ClearButton label={field.label} onClear={() => onChange('')} />
                </span>
            )}
            {field.suffix && <span className={classes.addon}>{field.suffix}</span>}
        </div>
    );
}
