// packages/vue/src/fields/Toggle.vue
<script setup lang="ts">
import { computed } from 'vue';
import { classes, cx, type BooleanFieldSchema } from '../../../core/src';
import type { FieldComponentEmits, FieldComponentProps } from '../types';

const props = defineProps<FieldComponentProps<BooleanFieldSchema>>();
const emit = defineEmits<FieldComponentEmits>();

const checked = computed(() => props.modelValue === props.field.trueValue);
const stateLabel = computed(() => (checked.value ? props.field.onLabel : props.field.offLabel));

function toggle() {
    emit('update:modelValue', checked.value ? props.field.falseValue : props.field.trueValue);
}
</script>

<template>
    <div :class="classes.toggleRow">
        <button
            :id="id"
            type="button"
            role="switch"
            :aria-checked="checked"
            :aria-invalid="error ? true : undefined"
            :aria-describedby="describedBy"
            :disabled="disabled || field.readonly"
            :autofocus="field.autofocus"
            :class="classes.toggleTrack"
            @click="toggle"
        >
            <span
                aria-hidden="true"
                :class="cx(classes.toggleThumb, checked && classes.toggleThumbOn)"
            />
        </button>
        <span v-if="stateLabel" :class="classes.toggleText" aria-hidden="true">{{
            stateLabel
        }}</span>
    </div>
</template>

// packages/react/src/fields/Toggle.tsx
import { classes, cx, type BooleanFieldSchema } from '../../../core/src';
import type { FieldComponentProps } from '../types';

export function Toggle({
    field,
    id,
    value,
    error,
    disabled,
    describedBy,
    onChange,
}: FieldComponentProps<BooleanFieldSchema>) {
    const checked = value === field.trueValue;
    const stateLabel = checked ? field.onLabel : field.offLabel;

    return (
        <div className={classes.toggleRow}>
            <button
                id={id}
                type="button"
                role="switch"
                aria-checked={checked}
                aria-invalid={error ? true : undefined}
                aria-describedby={describedBy}
                disabled={disabled || field.readonly}
                autoFocus={field.autofocus}
                className={classes.toggleTrack}
                onClick={() => onChange(checked ? field.falseValue : field.trueValue)}
            >
                <span
                    aria-hidden="true"
                    className={cx(classes.toggleThumb, checked && classes.toggleThumbOn)}
                />
            </button>
            {stateLabel && (
                <span className={classes.toggleText} aria-hidden="true">
                    {stateLabel}
                </span>
            )}
        </div>
    );
}
