// packages/react/src/WizardSteps.tsx
import {
    classes,
    wizardCircleClass,
    wizardProgress,
    wizardStepIcon,
    wizardStepLabel,
    wizardStepState,
    type FieldsetSchema,
} from '../../core/src';
import { Icon } from './Icon';

interface WizardStepsProps {
    steps: FieldsetSchema[];
    current: number;
    /** Go back to a completed step. */
    onSelect: (index: number) => void;
}

/**
 * The stepper above a wizard form. Completed steps are buttons that go back;
 * narrow screens only show the current step.
 */
export function WizardSteps({ steps, current, onSelect }: WizardStepsProps) {
    const currentStep = steps[current];

    return (
        <nav aria-label="Progress" className={classes.wizardNav}>
            {currentStep && (
                <div className={classes.wizardCompact}>
                    <p className={classes.wizardCompactCount}>
                        {`Step ${current + 1} of ${steps.length}`}
                    </p>
                    <p className={classes.wizardCompactTitle}>
                        {wizardStepLabel(currentStep, current)}
                    </p>
                    <div className={classes.wizardCompactTrack} aria-hidden="true">
                        <span
                            className={classes.wizardCompactBar}
                            style={{ width: wizardProgress(current, steps.length) }}
                        />
                    </div>
                </div>
            )}
            <ol className={classes.wizardList}>
                {steps.map((fieldset, index) => {
                    const state = wizardStepState(index, current);
                    const icon = wizardStepIcon(fieldset);
                    const content = (
                        <>
                            <span className={wizardCircleClass(state)} aria-hidden="true">
                                {state === 'complete' ? (
                                    <Icon name="check" className={classes.wizardCircleIcon} />
                                ) : icon || fieldset.iconSvg ? (
                                    <Icon
                                        name={icon}
                                        svg={fieldset.iconSvg}
                                        className={classes.wizardCircleIcon}
                                    />
                                ) : (
                                    index + 1
                                )}
                            </span>
                            <span className={classes.wizardStepText}>
                                <span
                                    className={
                                        state === 'upcoming'
                                            ? classes.wizardStepTitleUpcoming
                                            : classes.wizardStepTitle
                                    }
                                >
                                    {wizardStepLabel(fieldset, index)}
                                </span>
                                {fieldset.description && (
                                    <span className={classes.wizardStepDescription}>
                                        {fieldset.description}
                                    </span>
                                )}
                            </span>
                        </>
                    );

                    return (
                        <li
                            key={fieldset.id ?? index}
                            className={classes.wizardItem}
                            aria-current={state === 'current' ? 'step' : undefined}
                        >
                            {state === 'complete' ? (
                                <button
                                    type="button"
                                    className={classes.wizardStepButton}
                                    onClick={() => onSelect(index)}
                                >
                                    {content}
                                </button>
                            ) : (
                                <div className={classes.wizardStepStatic}>{content}</div>
                            )}
                            {index < steps.length - 1 && (
                                <span
                                    aria-hidden="true"
                                    className={
                                        index < current
                                            ? classes.wizardConnectorComplete
                                            : classes.wizardConnector
                                    }
                                />
                            )}
                        </li>
                    );
                })}
            </ol>
        </nav>
    );
}

// packages/svelte/src/lib/WizardSteps.svelte
<script lang="ts">
    import {
        classes,
        wizardCircleClass,
        wizardProgress,
        wizardStepIcon,
        wizardStepLabel,
        wizardStepState,
        type FieldsetSchema,
    } from './core';
    import Icon from './Icon.svelte';

    /**
     * The stepper above a wizard form. Completed steps are buttons that go back;
     * narrow screens only show the current step.
     */
    interface Props {
        steps: FieldsetSchema[];
        current: number;
        /** Go back to a completed step. */
        onSelect: (index: number) => void;
    }

    let { steps, current, onSelect }: Props = $props();
    const currentStep = $derived(steps[current]);
</script>

{#snippet content(fieldset: FieldsetSchema, index: number)}
    {@const state = wizardStepState(index, current)}
    {@const icon = wizardStepIcon(fieldset)}
    <span class={wizardCircleClass(state)} aria-hidden="true">
        {#if state === 'complete'}
            <Icon name="check" class={classes.wizardCircleIcon} />
        {:else if icon || fieldset.iconSvg}
            <Icon name={icon} svg={fieldset.iconSvg} class={classes.wizardCircleIcon} />
        {:else}
            {index + 1}
        {/if}
    </span>
    <span class={classes.wizardStepText}>
        <span
            class={state === 'upcoming' ? classes.wizardStepTitleUpcoming : classes.wizardStepTitle}
            >{wizardStepLabel(fieldset, index)}</span
        >
        {#if fieldset.description}
            <span class={classes.wizardStepDescription}>{fieldset.description}</span>
        {/if}
    </span>
{/snippet}

<nav aria-label="Progress" class={classes.wizardNav}>
    {#if currentStep}
        <div class={classes.wizardCompact}>
            <p class={classes.wizardCompactCount}>{`Step ${current + 1} of ${steps.length}`}</p>
            <p class={classes.wizardCompactTitle}>{wizardStepLabel(currentStep, current)}</p>
            <div class={classes.wizardCompactTrack} aria-hidden="true">
                <span
                    class={classes.wizardCompactBar}
                    style:width={wizardProgress(current, steps.length)}
                ></span>
            </div>
        </div>
    {/if}
    <ol class={classes.wizardList}>
        {#each steps as fieldset, index (fieldset.id ?? index)}
            <li class={classes.wizardItem} aria-current={index === current ? 'step' : undefined}>
                {#if index < current}
                    <button
                        type="button"
                        class={classes.wizardStepButton}
                        onclick={() => onSelect(index)}
                    >
                        {@render content(fieldset, index)}
                    </button>
                {:else}
                    <div class={classes.wizardStepStatic}>{@render content(fieldset, index)}</div>
                {/if}
                {#if index < steps.length - 1}
                    <span
                        aria-hidden="true"
                        class={index < current
                            ? classes.wizardConnectorComplete
                            : classes.wizardConnector}
                    ></span>
                {/if}
            </li>
        {/each}
    </ol>
</nav>
